// Generated by ts-to-zod
import { z } from "zod";

export const table1Schema = z.object({
    id: z.string(),
    name: z.string(),
    status: z.union([z.literal("active"), z.literal("inactive"), z.literal("pending")]),
    value: z.number(),
    itemCount: z.number().optional(),
    isVerified: z.boolean(),
    createdDate: z.string(),
    description: z.string().optional()
});
