// Generated by ts-to-zod
import { z } from "zod";

export const table2Schema = z.object({
    id: z.string(),
    table1Id: z.string().optional(),
    title: z.string(),
    amount: z.number(),
    priority: z.union([z.literal("low"), z.literal("medium"), z.literal("high")]),
    percentage: z.number().optional(),
    notes: z.string().optional(),
    isActive: z.boolean()
});
